apiVersion: v1
kind: Template
metadata:
  name: limesurvey-template
  annotations:
    description: "Template to create limesurvey service using mysql persistent data"
    tags: "limesurvey"
parameters:
- description: Password used for MySQL authentication
  from: '[A-Z0-9]{8}'
  generate: expression
  name: MYSQL_PASSWORD
objects:
- apiVersion: v1
  kind: Pod
  metadata:
    name: limesurvey
  labels:
    docker-registry: limesurvey
  spec:
    containers:
    - env:
      - name: MYSQL_PASSWORD
        value: ${MYSQL_PASSWORD}
      image: fjudith/limesurvey
      name: limesurvey
      ports:
      - containerPort: 6379
        protocol: TCP
labels:
  limesurvey: persistent